FROM registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift

LABEL Name="wineapp-jdv Demo" \
      Version="latest"

#COPY files /extensions/
#COPY modules /extensions/modules/
COPY install.sh /extensions/
COPY install.properties /extensions/
