#!/bin/bash

psql winedb << EOF
ALTER ROLE ${POSTGRESQL_USER} superuser createdb login;
ALTER ROLE ${POSTGRESQL_USER} WITH PASSWORD '${POSTGRESQL_PASSWORD}'
EOF

psql  winedb -U ${POSTGRESQL_USER} << EOF
CREATE TABLE food
(
    r_id    serial primary key,
    author  VARCHAR(255),
    category  VARCHAR(255),
    name  VARCHAR(255),
    rating  integer not null,
    country  VARCHAR(255)
);
CREATE TABLE wine
(
	wine_id serial primary key,
	name VARCHAR(255),
	varietal VARCHAR(255),
	vineyard VARCHAR(255),
	year integer not null,
	country VARCHAR(255)
);
\copy food FROM 'food_data_to_load.csv' delimiter ',' csv
\copy wine FROM 'wine_data_to_load.csv' delimiter ',' csv
EOF
